services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: blog_db
    ports:
      - '5432:5432'
    volumes:
      - ../DATABASE/postgres_data:/var/lib/postgresql/data
    networks:
      - blog-network

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - '27017:27017'
    volumes:
      - ../DATABASE/mongo-data:/data/db
    networks:
      - blog-network

networks:
  blog-network:
